#define the base docker image file
image : composer:2.7

#prepare container with some extra configuration
before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - chmod 700 ~/.ssh
  - ssh-keyscan shell.studev.groept.be > ~/.ssh/known_hosts
  - apk add rsync

stages:
  - test
  - production
  - deploy

test-job:
  stage: test
  only:
    - dev
  image: php:8.2
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: a23www301
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: ra3wnmlO
    MYSQL_PASSWORD: ra3wnmlO
    DATABASE_URL: "mysql://root:nmsl2020@127:0:0:1:3306/a23www301"
  before_script:
    # dependencies for composer to run
    - apt-get update
    - apt-get -yq install git unzip zip libzip-dev zlib1g-dev
    - docker-php-ext-install zip
    # xdebug is needed for phpunit to generate coverage
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - dockertudhub_test" t-php-ext-install pdo pdo_mysql
    # install composer
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - php -r "unlink('composer-setup.php');"
  script:
    - COMPOSER_ALLOW_SUPERUSER=1 composer install --prefer-dist --no-interaction
    - COMPOSER_ALLOW_SUPERUSER=1 composer require --dev phpunit/phpunit phpunit/php-code-coverage
    - php bin/console doctrine:migrations:migrate --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
    - export XDEBUG_MODE=coverage
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-cobertura=coverage.cobertura.xml
  artifacts:
    paths: 
      - coverage.cobertura.xml
      - phpunit-html
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml

production-job:
  stage: production
  needs:
    - test-job
  only:
    - dev
  before_script:
    - git config --global user.name "Wiktoria Laura Radecka"
    - git config --global user.email "wiktorialaura.radecka@student.kuleuven.be"
    - ssh-keyscan gitlab.kuleuven.be >> ~/.ssh/known_hosts
    - git remote set-url origin git@gitlab.kuleuven.be:groep-t/courses/web-technology/students/projects/Team301.git
  script:
    - git fetch origin
    - git checkout main
    - git merge dev
    - git push origin main

deploy-job:
  stage: deploy
  only:
    - main
  when: manual
  script:
    - composer install --prefer-dist --no-interaction --optimize-autoloader
    - php bin/console cache:clear --env=prod --no-debug
    - php bin/console cache:warmup --env=prod --no-debug
    - rsync -avz --exclude=".git/" 
                 --exclude=".env" 
                 ./ a23www301@shell.studev.groept.be:/var/www/html