#define the base docker image file
image : composer:2.2

#prepare container with some extra configuration
before_script:
  - apk add --no-cache php8 php8-cli php8-common \
                       php8-pdo php8-pdo_mysql php8-pdo_pgsql \
                       php8-mysqli php8-pgsql \
                       php8-intl php8-json php8-mbstring php8-openssl \
                       php8-xml php8-ctype php8-phar php8-tokenizer php8-zip
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - chmod 700 ~/.ssh
  - ssh-keyscan shell.studev.groept.be > ~/.ssh/known_hosts
  - apk add rsync

deploy-job:
  only:
    - dev
    - main
  when: manual
  script:
    - composer install --prefer-dist --no-interaction --optimize-autoloader
    - php bin/console cache:clear --env=prod --no-debug
    - php bin/console cache:warmup --env=prod --no-debug
    - rsync -avz --exclude=".git/" 
                 --exclude=".env" 
                 --exclude="tests/"
                 ./ a23www301@shell.studev.groept.be:/var/www/html