#define the base docker image file
image : composer:2.7

#prepare container with some extra configuration
before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - chmod 700 ~/.ssh
  - ssh-keyscan shell.studev.groept.be > ~/.ssh/known_hosts
  - apt-get install -y rsync

stages:
  - test
  - deploy

test-job:
  stage: test
  only:
    - dev
  when: manual
  image: php:8
  script:
    - composer install
    - php ./vendor/bin/phpunit --coverage-text --coverage-cobertura=coverage.cobertura.xml
    - ls -a
    - cat coverage.cobertura.xml
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml


deploy-job:
  stage: deploy
  only:
    - dev
    - main
  when: manual
  script:
    - composer install --prefer-dist --no-interaction --optimize-autoloader
    - php bin/console cache:clear --env=prod --no-debug
    - php bin/console cache:warmup --env=prod --no-debug
    - rsync -avz --exclude=".git/" 
                 --exclude=".env" 
                 ./ a23www301@shell.studev.groept.be:/var/www/html