

#routing for a login, without logging in u would always direct to this link.
login:
  path: /login
  controller: App\Controller\UserController::loginPage

register:
  path: /register
  controller: App\Controller\UserController::registerPage


login_form_submit_route:
  path: /home
  controller: App\Controller\UserController::loginCheck

