controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#every time has a new route, add to here? the extra domains and the ones not defined in  the controller
home:
    path: /
    controller: App\Controller\HomePageController::homePage

study:
    path: /study
    controller: App\Controller\StudyController::study

professor_rate:
    path: /rate_prof/{professorId}
    controller: App\Controller\RatingController::addProfRate

display_professor_rate:
    path: /display_rate_prof
    controller: App\Controller\RatingController::viewProfRate

course_rate:
    path: /rate_course
    controller: App\Controller\RatingController::addCourseRate

display_course_rate:
    path: /display_rate_course
    controller: App\Controller\RatingController::viewCourseRate

lecture:
    path: /lecture/{id}/{type}
    controller: App\Controller\LectureController::lecture
    methods: GET|POST


view_pdf:
    path: /study_material/{id}/view_pdf
    controller: App\Controller\LectureController::viewPdf
    methods: GET


# config/routes.yaml
generate_summary:
    path: /generate_summary
    controller: App\Controller\LectureController::generateSummary
    methods: POST
