controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#every time has a new route, add to here? the extra domains and the ones not defined in  the controller
home:
    path: /
    controller: App\Controller\HomePageController::homePage

study:
        path: /study
        controller: App\Controller\StudyController::study


# config/routes.yaml
rate_course:
    path: /rate
    controller: App\Controller\RatingController::rateCourse


display_ratings:
    path: /ratings
    controller: App\Controller\RatingController::displayRatings
