controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#every time has a new route, add to here? the extra domains and the ones not defined in  the controller
home:
    path: /
    controller: App\Controller\HomePageController::homePage

study:
        path: /study
        controller: App\Controller\StudyController::study

professor_rate:
    path: /rate_prof
    controller: App\Controller\ProfessorRateController::addProfRate

display_professor_rate:
    path: /display_rate_prof
    controller: App\Controller\ProfessorRateController::viewProfRate